"use client";
import {useEffect,useState} from "react";
type P={id:number;name:string;job:string;emoji:string;x:number;y:number;gold:number;mood:string};
const raw:any[]=[["ガンツ","鍛冶屋","🔨",29,39,420,"上機嫌"],["ミラ","薬屋","🧪",61,33,310,"忙しい"],["ロッタ","宿屋","🛏️",48,61,580,"穏やか"],["エルン","パン屋","🥖",74,58,190,"眠い"],["ノア","旅人","🎒",18,64,125,"好奇心"],["レオ","勇者","⚔️",8,47,860,"探索中"],["ユナ","僧侶","✨",11,51,440,"探索中"],["カイ","魔法使い","🔮",14,48,510,"探索中"]];
const base:P[]=raw.map((a,i)=>({id:i,name:a[0],job:a[1],emoji:a[2],x:a[3],y:a[4],gold:a[5],mood:a[6]}));
const events=["勇者一行が西門からやってきた！","鍛冶屋ガンツが鉄の剣を値下げした","薬屋ミラのポーションが売れた +18G","宿屋ロッタ、本日あと2部屋","広場で旅人が古い地図の噂をしている","パンの香りにつられて住民が集まってきた","北の森で魔物の目撃情報…","勇者レオが武器屋をじっと見ている"];
export default function Home(){const [tick,setTick]=useState(18432);const [people,setPeople]=useState(base);const [feed,setFeed]=useState(events.slice(0,4));const [sel,setSel]=useState<P|null>(null);
useEffect(()=>{const t=setInterval(()=>{setTick(v=>v+1);setPeople(ps=>ps.map(p=>({...p,x:Math.max(5,Math.min(91,p.x+(Math.random()-.45)*2.2)),y:Math.max(18,Math.min(84,p.y+(Math.random()-.5)*1.5))})));if(Math.random()>.56)setFeed(f=>[events[Math.floor(Math.random()*events.length)],...f].slice(0,5))},1200);return()=>clearInterval(t)},[]);
const hour=Math.floor((tick/30)%24),day=Math.floor(tick/720)+1,night=hour<6||hour>18,gdp=18420+tick%370;
return <main className={night?"night":""}><header><div><b>REAL NPC</b><span> LIVING WORLD / ALPHA</span></div><div className="live">● LIVE　DAY {day}　{String(hour).padStart(2,"0")}:{String((tick*2)%60).padStart(2,"0")}</div></header><section className="stats"><div><small>人口</small><strong>97</strong><em>人</em></div><div><small>町GDP</small><strong>{gdp.toLocaleString()}</strong><em>G</em></div><div><small>来訪勇者</small><strong>3</strong><em>人</em></div><div><small>人気職業</small><strong>鍛冶屋</strong></div></section><section className="world"><div className="map"><div className="river"/><div className="road h"/><div className="road v"/><Building x={22} y={24} icon="⚒️" name="鉄火の鍛冶屋"/><Building x={62} y={21} icon="🧪" name="月灯り薬店"/><Building x={37} y={58} icon="🏨" name="旅籠ロッタ"/><Building x={70} y={61} icon="🥖" name="麦のパン屋"/><Building x={45} y={30} icon="⛲" name="中央広場"/><div className="gate">西門</div>{people.map(p=><button key={p.id} className="person" style={{left:p.x+"%",top:p.y+"%"}} onClick={()=>setSel(p)}><i>{p.emoji}</i><label>{p.name}</label>{p.id===5&&<span className="bubble">武器を見ていこう</span>}</button>)}<div className="trees">🌲　🌳　🌲　　　　　🌳<br/>　　🌲　　　　　　　　　🌲</div></div><aside><h2>町のいま</h2>{feed.map((e,i)=><div className="event" key={i}><time>{i?(i*3+1)+"分前":"たった今"}</time><p>{e}</p></div>)}<h2>WORLD PULSE</h2><div className="pulse">市場 <b>安定</b><br/>治安 <b>良好</b><br/>勇者誘引 <b>↑ 12%</b></div></aside></section>{sel&&<div className="card" onClick={()=>setSel(null)}><div className="portrait">{sel.emoji}</div><div><small>{sel.job}</small><h3>{sel.name}</h3><p>所持金 {sel.gold}G　・　{sel.mood}</p><q>{sel.id===0?"勇者が来たな。今日は一本売れるかもな。":"今日もこの町は騒がしいね。"}</q></div><button>×</button></div>}<footer>WORLD TICK #{tick.toLocaleString()}　•　この町はあなたが見ていない間も生き続けます</footer></main>}
function Building({x,y,icon,name}:{x:number,y:number,icon:string,name:string}){return <div className="building" style={{left:x+"%",top:y+"%"}}><div>{icon}</div><span>{name}</span></div>}